spring.application.name=Use&Devolva
spring.datasource.url=jdbc:postgresql://ep-dry-bread-acofwpya.sa-east-1.aws.neon.tech/postgres?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nXm4LWx6Kjyq
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect