spring.application.name=Use&Devolva
spring.datasource.url=jdbc:postgresql://db.ppfpeuasxauydpwbnsje.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=@CleytonButton2026
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect