spring.application.name=Use&Devolva
spring.datasource.url=jdbc:postgresql://db.ppfpeuasxauydpwbnsje.supabase.co:6543/postgres
spring.datasource.username=postgres
spring.datasource.password=[@CleytonButton2026]
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
